# 'Logistic Regression': {
#                     'penalty':[None, '12', 'l1', 'elasticnet'],
#                     'dual':[True,False],
#                     'solver':['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
#                 },
#                 'SVM':{
#                     'C':[0.1, 1, 10, 1000],
#                     'kernel':['linear', 'poly', 'rbf', 'sigmoid'],
#                     'degree':[0, 1, 2, 3, 4, 5, 6],
#                     'gamma':['scale', 'auto'],
                  
#                 },
#                 "Random Forest":{
#                     'criterion':['gini', 'entropy', 'log_loss'],
#                     'max_features':['sqrt','log2',None],
#                     'n_estimators': [8, 16, 32, 64, 128, 256],
#                     'max_leaf_nodes': [None, 8, 16, 32 ],
#                     'bootstrap': [True, False],
#                     'n_jobs': [1, -1],
#                     'max_samples': [2, 4,6],
#                     'min_samples_split': np.arange(2, 20, 2),
#                     'min_samples_leaf': np.arange(1, 20, 2)
#                 },
#                 'XGB':{
#                     'learning_rate': [0.01, 0.05, 0.1],
#                     'max_depth': [6, 8, 10],
#                     'gamma': [2, 4, 9, 12],
#                     'sampling_method': ['uniform', 'gradient_based'],
#                     'grow_policy': ['depthwise', 'lossguide'],
#                     'n_estimators': [8,16,32,64,128,256]
                    
#                 },
#                 'LightGBM':{
#                     'boosting_type':['gbdt', 'rf', 'dart'],
#                     'max_depth': [-1, 2, -10],
#                     'learning_rate': [0.01, 0.05, 0.1],
#                     'n_estimator': [100, 50, 200],
#                     'num_leaves': [31, 50, 100]
#                 },