artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  n_rows: 1000
  acquisition_source_data_file: data/acquisitions.csv
  cat_groups_source_data_file: data/category_groups.csv
  degrees_source_data_file: data/degrees.csv
  event_appearances_source_data_file: data/event_appearances.csv
  events_source_data_file: data/events.csv
  funding_rounds_source_data_file: data/funding_rounds.csv
  funds_source_data_file: data/funds.csv
  investments_partners_source_data_file: data/investment_partners.csv
  investments_source_data_file: data/investments.csv
  investors_source_data_file: data/investors.csv
  ipos_source_data_file: data/ipos.csv
  jobs_source_data_file: data/jobs.csv
  org_parents_source_data_file: data/org_parents.csv
  organization_descriptions_source_data_file: data/organization_descriptions.csv
  organizations_source_data_file: data/organizations.csv
  people_source_data_file: data/people.csv
  people_descriptions_source_data_file: data/people_descriptions.csv

  acquisition_local_data_file: artifacts/data_ingestion/acquisitions.csv
  cat_groups_local_data_file: artifacts/data_ingestion/category_groups.csv
  degrees_local_data_file: artifacts/data_ingestion/degrees.csv
  event_appearances_local_data_file: artifacts/data_ingestion/event_appearances.csv
  events_local_data_file: artifacts/data_ingestion/events.csv
  funding_rounds_local_data_file: artifacts/data_ingestion/funding_rounds.csv
  funds_local_data_file: artifacts/data_ingestion/funds.csv
  investments_partners_local_data_file: artifacts/data_ingestion/investment_partners.csv
  investments_local_data_file: artifacts/data_ingestion/investments.csv
  investors_local_data_file: artifacts/data_ingestion/investors.csv
  ipos_local_data_file: artifacts/data_ingestion/ipos.csv
  jobs_local_data_file: artifacts/data_ingestion/jobs.csv
  org_parents_local_data_file: artifacts/data_ingestion/org_parents.csv
  organization_descriptions_local_data_file: artifacts/data_ingestion/organization_descriptions.csv
  organizations_local_data_file: artifacts/data_ingestion/organizations.csv
  people_local_data_file: artifacts/data_ingestion/people.csv
  people_descriptions_local_data_file: artifacts/data_ingestion/people_descriptions.csv


data_cleaning:
  root_dir: artifacts/data_cleaning
  acquisition_local_data_file: artifacts/data_cleaning/acquisitions.csv
  degrees_local_data_file: artifacts/data_cleaning/degrees.csv
  event_appearances_local_data_file: artifacts/data_cleaning/event_appearances.csv
  funding_rounds_local_data_file: artifacts/data_cleaning/funding_rounds.csv
  ipos_local_data_file: artifacts/data_cleaning/ipos.csv
  jobs_local_data_file: artifacts/data_cleaning/jobs.csv
  org_parents_local_data_file: artifacts/data_cleaning/org_parents.csv
  organization_descriptions_local_data_file: artifacts/data_cleaning/organization_descriptions.csv
  organizations_local_data_file: artifacts/data_cleaning/organizations.csv
  people_local_data_file: artifacts/data_cleaning/people.csv
  people_descriptions_local_data_file: artifacts/data_cleaning/people_descriptions.csv

  acquisition_column_to_drop: ['permalink', 'cb_url', 'rank', 'created_at',
     'updated_at', 'acquiree_cb_url','acquirer_cb_url', 'uuid', 'name', 'type', 'acquiree_name',
     'acquiree_country_code', 'acquiree_state_code', 'acquiree_region',
     'acquiree_city','acquirer_country_code', 'acquirer_state_code', 'acquirer_region',
     'acquirer_city', 'acquisition_type','price', 'price_currency_code']
  acquisition_column_to_rename: {'acquiree_uuid':'org_uuid'}
  degrees_column_to_drop: ['name','rank','permalink','cb_url','created_at','updated_at',
                           'uuid','type','person_name']
  degrees_column_to_rename: {'started_on': 'degree_started_on', 'completed_on': 'degree_completed_on',
                      'is_completed': 'degree_is_completed'}
  degrees_column_to_drop_na: ['institution_uuid', 'institution_name', 'degree_type', 'subject',
                     'degree_started_on', 'degree_completed_on']
  event_appearances_column_to_drop: [ 'uuid', 'name', 'type', 'participant_type', 'permalink',
                      'cb_url', 'rank', 'created_at','updated_at', 'short_description']
  funding_rounds_column_to_drop: [ 'type', 'permalink', 'cb_url', 'created_at',
     'updated_at', 'uuid', 'name', 'rank', 'country_code', 'state_code', 'region', 'city',
      'raised_amount','raised_amount_currency_code', 'org_name',
     'lead_investor_uuids', 'post_money_valuation', 'post_money_valuation_currency_code']
  ipos_column_to_drop: ['name', 'permalink', 'cb_url', 'rank', 'created_at','updated_at', 'org_cb_url', 'uuid',
         'org_name', 'country_code', 'state_code', 'region', 'city', 'stock_exchange_symbol', 'stock_symbol',
          'share_price', 'share_price_currency_code', 'valuation_price',
         'valuation_price_currency_code', 'money_raised', 'money_raised_currency_code']
  ipos_column_to_rename: {'type': 'ipos_type'}
  jobs_column_to_drop: ['type', 'permalink', 'cb_url', 'rank', 'created_at','updated_at',
         'person_name', 'org_uuid', 'org_name']
  jobs_column_to_rename: {'started_on': 'job_started_on', 'ended_on': 'job_ended_on',
                      'is_current': 'job_is_current', 'title': 'job_title'}
  jobs_column_to_drop_na: ['name','person_uuid', 'job_title']
  org_parents_column_to_drop: ['permalink', 'cb_url', 'created_at','updated_at', 'rank']
  org_parents_column_to_rename: {'uuid': 'org_uuid', 'name': 'org_name'}
  organizations_column_to_drop: ['permalink', 'cb_url', 'created_at',
                                 'updated_at', 'num_funding_rounds', 'total_funding', 'total_funding_currency_code',
                                 'logo_url', 'alias1', 'alias2', 'alias3', 'num_exits',
                                 'email', 'phone', 'short_description', 'legal_name', 'domain',
                                 'homepage_url', 'country_code', 'state_code', 'region', 'city',
                                 'address', 'postal_code', 'type']
  organizations_column_to_drop_na: ['twitter_url', 'facebook_url', 'founded_on']
  organization_descriptions_column_to_drop: [ 'type', 'permalink', 'cb_url', 'created_at','updated_at',
                                              'name', 'rank']
  organization_descriptions_column_to_rename: {'description': 'organization_description'}
  organization_descriptions_column_to_drop_na: ['uuid']
  people_column_to_drop: ['type', 'permalink', 'rank', 'created_at','updated_at','cb_url','logo_url', 'name',
          'country_code', 'state_code', 'region', 'city']
  people_column_to_rename: {'uuid': 'person_uuid', 'facebook_url': 'people_facebook_url', 'linkedin_url': 'people_linkedin_url',
                         'twitter_url': 'people_twitter_url'}
  people_column_to_drop_na: ['first_name', 'last_name', 'featured_job_organization_uuid']
  people_descriptions_column_to_drop: [ 'type', 'permalink', 'cb_url','created_at','updated_at', 'name', 'rank']
  people_descriptions_column_to_rename: {'uuid': 'person_uuid', 'description': 'people_description'}

  degree_completed_on: degree_completed_on
  degree_started_on: degree_started_on
  founded_on: founded_on
  closed_on: closed_on
  last_funding_on: last_funding_on
  description: description
  job_started_on: job_started_on
  job_ended_on: job_ended_on
  employee_count: employee_count
  organization_description: organization_description
  people_description: people_description

  uuid: uuid
  featured_job_organization_uuid: featured_job_organization_uuid
  person_uuid: person_uuid
  event_group_by: ['participant_uuid', 'appearance_type']
  event_uuid: event_uuid
  participant_uuid: participant_uuid
  appearance_type: appearance_type
  org_uuid: org_uuid
  clean_backbone_local_data_file: artifacts/data_cleaning/clean_backbone.csv
  success_column_to_drop: [ 'acquirer_uuid', 'acquirer_name', 'acquired_on','price_usd', 'investment_type',
                            'announced_on', 'raised_amount_usd', 'post_money_valuation_usd', 'investor_count',
                            'went_public_on', 'share_price_usd', 'valuation_price_usd', 'money_raised_usd']

data_scrapping:
  root_dir: artifacts/data_scrapping
  chrome_driver_path: src/chromedriver.exe
  unclean_backbone_local_data_file: artifacts/data_cleaning/unclean_backbone.csv
  twitter_url: twitter_url
  facebook_url: facebook_url
  twitter_username: SoyinkaSoy
  twitter_password: Olatunde1$
  df_rows: 5
  max_tweets: 10
  facebook_username: SoyinkaSoy
  facebook_password: Olatunde1$

data_enrich:
  root_dir: artifacts/data_enrich
  enriched_backbone_local_data_file: artifacts/data_enrich/enrich_unclean_backbone.csv
  twitter_sentiment_local_data_file: artifacts/data_enrich/twitter_sentiments.csv
  column_to_load: ['account', 'text', 'follower_data', 'following_data']
  follower_data: follower_data
  following_data: following_data
  account: account
  polarity: polarity
  subjectivity: subjectivity
  tweet_analysis: tweet_analysis
  text: text
  enrich_data_columns: ['following', 'followers', 'polarity',
                                          'subjectivity', 'twitter_url']

data_transformation:
    root_dir: artifacts/data_transformation
    clean_backbone_local_data_file: artifacts/data_cleaning/unclean_backbone.csv
    transformed_data_local_data_file: artifacts/data_transformation/transformed_data.csv
    train_data_local_data_file: artifacts/data_transformation/train_data.csv
    validate_data_local_data_file: artifacts/data_transformation/validate_data.csv
    test_data_local_data_file: artifacts/data_transformation/test_data.csv
    per_exp_at_coy_start: per_exp_at_coy_start
    founded_on: founded_on
    closed_on: closed_on
    degree_completed_on: degree_completed_on
    degree_length: degree_length
    yrs_since_last_funding: yrs_since_last_funding
    yrs_of_operation: yrs_of_operation
    columns_to_parse_dates: ['founded_on','last_funding_on','closed_on','degree_started_on',
                                                    'degree_completed_on'] 
    columns_to_drop: ['founded_on','closed_on','facebook_url','linkedin_url','twitter_url','person_uuid',
               'founded_on','last_funding_on', 'first_name','last_name', 'featured_job_organization_uuid', 'featured_job_organization_name',
               'people_facebook_url', 'people_linkedin_url', 'people_twitter_url', 'institution_uuid',
               'degree_started_on', 'degree_completed_on', 'org_uuid','rank','uuid','name','type', 'roles']
    columns_rearrangement: ['yrs_of_operation', 'yrs_since_last_funding', 'degree_length', 'per_exp_at_coy_start', 'sponsor','speaker',
                'organizer','exhibitor', 'employee_count', 'total_funding_usd', 'organization_description','people_description',
                 'status', 'category_list', 'category_groups_list', 'primary_role',
                 'gender', 'featured_job_title', 'institution_name', 'degree_type', 
                'subject', 'degree_is_completed','success']
    institution_name: institution_name
    degree_type: degree_type
    subject: subject
    degree_is_completed: degree_is_completed
    exhibitor: exhibitor
    organizer: organizer
    speaker: speaker 
    sponsor: sponsor
    last_funding_on: last_funding_on
    employee_cap_success: 1000
    employee_count: employee_count
    success: success
    uuid: uuid
    train_percent: 0.6
    validate_percent: 0.2
    test_percent: 0.2
    # Create a list of feature categorisations
    num_features: ['yrs_of_operation', 'yrs_since_last_funding', 'degree_length', 'per_exp_at_coy_start', 
                      'sponsor', 'speaker', 'organizer', 'exhibitor', 'employee_count', 'total_funding_usd']
    text_feature_o: 'organization_description'
    text_feature_p: 'people_description'
    cat_features: [  'status', 'category_list', 
                      'category_groups_list', 'primary_role', 'gender', 
                      'featured_job_title', 'institution_name', 'degree_type',
                      'subject', 'degree_is_completed']
    preprocessor_obj_path: artifacts/data_transformation/preprocessor.pkl

model_trainer: 
    root_dir: artifacts/model_trainer
    train_data_path: artifacts/data_transformation/train_arr.csv
    validation_data_path: artifacts/data_transformation/val_arr.csv
    test_data_path: artifacts/data_transformation/test_arr.csv
    best_model_path: artifacts/model_trainer/best_model.pkl   
    models:
        Logistic Regression: sklearn.linear_model.LogisticRegression
        SVM: sklearn.svm.SVC
        Random Forest: sklearn.ensemble.RandomForestClassifier
        XGB: xgboost.XGBClassifier
        LightGBM: lightgbm.LGBMClassifier
 
prediction_pipeline:
      per_exp_at_coy_start: per_exp_at_coy_start 
      degree_length: degree_length
      yrs_since_last_funding: yrs_since_last_funding
      yrs_of_operation: yrs_of_operation
      institution_name: institution_name
      degree_type: degree_type
      subject: subject
      degree_is_completed: degree_is_completed
      exhibitor: exhibitor
      organizer: organizer
      speaker: speaker
      sponsor: sponsor
      last_funding_amount: last_funding_amount
      employee_count: employee_count
      model_path: artifacts/model_trainer/best_model.pkl
      preprocessor_obj_path: artifacts/data_transformation/preprocessor.pkl


    
   

